### ISSUE TITLE
Switching back to app does not hide splash screen.

### ISSUE THREAD

**Issue by leouze** [devgeeks/PrivacyScreenPlugin#12] opened 2016-02-23 05:56 UTC
Hi @devgeeks 
First of all thank you for this plugin it works except that switching back from the app does not hide the splash screen.

Steps to reproduce.
1) Open the app.
2) Move the app to background by tapping home button
3) Tap the app again

**Comment by joel-caton** [comment] 2016-02-23 19:27
You'll have to apply the fix from https://github.com/devgeeks/PrivacyScreenPlugin/pull/8 to get this plugin to work. 

I tried using this on iOS and eventually just used the splashscreen plugin along with the onpause and on resume events to get what I needed.

**Comment by devgeeks** [comment] 2016-02-23 19:31
This is odd. I am not experiencing this on any of my apps using it.

I'll have a look as soon as I can and look at the PR as well.

**Comment by barneydunning** [comment] 2016-02-29 14:55
Hi there,

We are having this issue too on iOS (v9) - can anyone help?  On Android, the plugin works as expected, but on iOS we are having issues. 

It appears that when you put the app to the background... you get correctly a black screen (or the splash screen) in the iOS app-swiper... but if you touch the app to bring it back to the foreground, the black (or splash) screen persists.  To recover, you have to shut down the app and restart it.

This is a real pain because the plugin is exactly what we need in our application as it contains sensitive data... which leads me to my final question... does this application protect against taking a screenshot?

Hope someone out there can help...

Barney

**Comment by shaoyunli** [comment] 2016-02-29 15:17
@devgeeks Same issue I have here on iOS (v8.1). I have a splash screen for the app, in the app-swiper, I got the splash screen shown but it persists until I shut down the app.

In addition, I also have a splash screen on Android, in the app-swiper, the splash screen does not show but a black screen. 

Another issue I have is related to taking screenshot. On Android, with your plugin, you cannot take screenshots of the app and an error message will show, "Could not take a screenshot. Content is protected by DRM." It would be nice if iOS can also disable the feature to take screenshot with your plugin. Is it possible to achieve that on iOS?

**Comment by mattalco** [comment] 2016-02-29 20:50
I am also having this problem. I created a vanilla Cordova app with the the 'phonegap-plugin-push' installed and can reproduce this issue 100% of the time.

My plugins are:
cordova-plugin-privacyscreen 0.1.2 "PrivacyScreenPlugin"
cordova-plugin-whitelist 1.2.1 "Whitelist"
phonegap-plugin-push 1.5.3 "PushPlugin"

**Comment by devgeeks** [comment] 2016-02-29 23:24
OK. I am going to make some time to look into this this weekend if not sooner.

@shaoyunli The Android version uses a built in Android feature called [FLAG_SECURE](http://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE) that stops screenshots and causes the black screen. Initially I had iOS do the same (pure black screen) but @EddyVerbruggen added the feature of showing the splash screen. iOS, however, has no easy way to disable screenshots (just ask SnapChat, etc, hehe).

@mattalco Is there a reason you are not yet using cordova-ios@4.x ? No idea if related to the problem, just curious. Also, in your repro, did you do any changes other than just installing the three plugins? Interestingly, this is the easiest way for me to repro this. I created a vanilla app. Added the privacy screen plugin. Ran the app and tested... worked fine. Added the push plugin, ran again... and I can now repro being stuck at the splash. :/ Remove the push plugin, try again... everything works again. ugh.

Are any of the rest of you using the push plugin? Any other plugins I might need to know about?

**Comment by devgeeks** [comment] 2016-02-29 23:38
I am speaking with the author of the push plugin, and it might be that since both plugins "swizzle" the AppDelegate, that they are clashing. It might be that the other folks experiencing this are using other plugins that do the same.

I'll work with him and see if we can find a solution.

Anyone NOT using the push plugin and still experiencing this? I would 💖a list of the other plugins you *are* using.

**Comment by joel-caton** [comment] 2016-02-29 23:48
Good catch.  I am using the push plugin.

**Comment by EddyVerbruggen** [comment] 2016-03-01 08:50
Let me take a stab at this if if I may.

**Comment by shaoyunli** [comment] 2016-03-01 08:58
I am using the phonegap-plugin-push plugin as well!!

**Comment by devgeeks** [comment] 2016-03-01 09:58
@EddyVerbruggen I think I've fixed it, but would love a review.

OK. If someone wants to test:

```
cordova plugin remove cordova-plugin-privacyscreen
cordova plugin add https://github.com/devgeeks/PrivacyScreenPlugin#issue-12
```
...that'd be awesome.

// @shaoyunli @joel-caton @mattalco

**Comment by shaoyunli** [comment] 2016-03-01 11:27
Thanks for the rapid fix @devgeeks.

I am using PhoneGap cloud to build the app and PhoneGap will use the latest release of the plugin. As your fix has not been available on the release yet (currently the version used by PhoneGap is 0.1.2), I cannot test the fix on my device. Would it be possible to update the release branch or make a new release? As soon as the fix is available to PhoneGap cloud, I will be able to test it.

**Comment by devgeeks** [comment] 2016-03-01 13:11
@shaoyunli I don't want to push to master and nam until I know it works.

Probably later today or tomorrow maybe.

**Comment by shaoyunli** [comment] 2016-03-01 13:50
Thanks. I will wait for that.

**Comment by mattalco** [comment] 2016-03-01 15:18
@devgeeks Cordova iOS 4.x has had some stability issues which has kept me from using it. https://issues.apache.org/jira/browse/CB-10276

I'll test this fix today. Thanks for the rapid turnaround :)

**Comment by mattalco** [comment] 2016-03-01 16:25
@devgeeks this fix works for me

**Comment by devgeeks** [comment] 2016-03-01 20:17
@mattalco it seems @EddyVerbruggen also sent a PR that removes even needing to swizzle AppDelegate in the first place. I am going to test that out a bit today as well. That might be an even better safer solution... then we can look at the problem of splash image availability (black screens) in cordova-ios@4 :/

**Comment by shaoyunli** [comment] 2016-03-08 15:40
@devgeeks have you got any progress to move this forward? When would you like to update or make a new release so that PhoneGap cloud build can pick up your latest fix? Thanks a lot!

**Comment by shaoyunli** [comment] 2016-03-09 12:16
Hi @devgeeks,

I have managed to add the plugin retrieved from the branch issue-12 to the online PhoneGap build by adding the follow config. 
<plugin spec="https://github.com/devgeeks/PrivacyScreenPlugin.git#issue-12"/>

I tested on both Android and iOS. The fix works. The only issue is on Android, in app-swiper, the splash screen does not show but a white screen shows. 

Thanks for fixing the problem. Could you please inform us when you update the master and make a new release? Then I will update the config to use the proper release version rather than the branch.

**Comment by devgeeks** [comment] 2016-03-10 03:24
Yeah, sorry :(

I have been short on time and I really wanna test the version without swizzling that Eddy sent in...

I will try to make a decision and merge to master and republish.

**Comment by stefanjauker** [comment] 2016-03-12 13:21
The Pull Request from Eddy looks good. Please merge it.

**Comment by devgeeks** [comment] 2016-03-15 00:03
Merged. Bumped. Published.

**Closed by devgeeks** 2016-03-15 00:03 UTC
